// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/orderdatamodel.proto

package com.packt.masteringakka.bookstore.inventory;

public final class OrderDatamodel {
  private OrderDatamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SalesOrderLineItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string bookId = 2;
    /**
     * <code>required string bookId = 2;</code>
     */
    boolean hasBookId();
    /**
     * <code>required string bookId = 2;</code>
     */
    java.lang.String getBookId();
    /**
     * <code>required string bookId = 2;</code>
     */
    com.google.protobuf.ByteString
        getBookIdBytes();

    // required int32 quantity = 3;
    /**
     * <code>required int32 quantity = 3;</code>
     */
    boolean hasQuantity();
    /**
     * <code>required int32 quantity = 3;</code>
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem}
   */
  public static final class SalesOrderLineItem extends
      com.google.protobuf.GeneratedMessage
      implements SalesOrderLineItemOrBuilder {
    // Use SalesOrderLineItem.newBuilder() to construct.
    private SalesOrderLineItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SalesOrderLineItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SalesOrderLineItem defaultInstance;
    public static SalesOrderLineItem getDefaultInstance() {
      return defaultInstance;
    }

    public SalesOrderLineItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SalesOrderLineItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              bookId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              quantity_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.class, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder.class);
    }

    public static com.google.protobuf.Parser<SalesOrderLineItem> PARSER =
        new com.google.protobuf.AbstractParser<SalesOrderLineItem>() {
      public SalesOrderLineItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SalesOrderLineItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SalesOrderLineItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string bookId = 2;
    public static final int BOOKID_FIELD_NUMBER = 2;
    private java.lang.Object bookId_;
    /**
     * <code>required string bookId = 2;</code>
     */
    public boolean hasBookId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string bookId = 2;</code>
     */
    public java.lang.String getBookId() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bookId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBookIdBytes() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 quantity = 3;
    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_;
    /**
     * <code>required int32 quantity = 3;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 quantity = 3;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    private void initFields() {
      bookId_ = "";
      quantity_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBookId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getBookIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, quantity_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBookIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.class, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bookId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_descriptor;
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem build() {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem buildPartial() {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem result = new com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bookId_ = bookId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.quantity_ = quantity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem) {
          return mergeFrom((com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem other) {
        if (other == com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.getDefaultInstance()) return this;
        if (other.hasBookId()) {
          bitField0_ |= 0x00000001;
          bookId_ = other.bookId_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBookId()) {
          
          return false;
        }
        if (!hasQuantity()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string bookId = 2;
      private java.lang.Object bookId_ = "";
      /**
       * <code>required string bookId = 2;</code>
       */
      public boolean hasBookId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public java.lang.String getBookId() {
        java.lang.Object ref = bookId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bookId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBookIdBytes() {
        java.lang.Object ref = bookId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public Builder setBookId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public Builder clearBookId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bookId_ = getDefaultInstance().getBookId();
        onChanged();
        return this;
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public Builder setBookIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookId_ = value;
        onChanged();
        return this;
      }

      // required int32 quantity = 3;
      private int quantity_ ;
      /**
       * <code>required int32 quantity = 3;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 quantity = 3;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>required int32 quantity = 3;</code>
       */
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000002;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quantity = 3;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem)
    }

    static {
      defaultInstance = new SalesOrderLineItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem)
  }

  public interface SalesOrderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    java.util.List<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem> 
        getLineItemList();
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem getLineItem(int index);
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    int getLineItemCount();
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    java.util.List<? extends com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder> 
        getLineItemOrBuilderList();
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder getLineItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.SalesOrder}
   */
  public static final class SalesOrder extends
      com.google.protobuf.GeneratedMessage
      implements SalesOrderOrBuilder {
    // Use SalesOrder.newBuilder() to construct.
    private SalesOrder(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SalesOrder(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SalesOrder defaultInstance;
    public static SalesOrder getDefaultInstance() {
      return defaultInstance;
    }

    public SalesOrder getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SalesOrder(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                lineItem_ = new java.util.ArrayList<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              lineItem_.add(input.readMessage(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          lineItem_ = java.util.Collections.unmodifiableList(lineItem_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.class, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder.class);
    }

    public static com.google.protobuf.Parser<SalesOrder> PARSER =
        new com.google.protobuf.AbstractParser<SalesOrder>() {
      public SalesOrder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SalesOrder(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SalesOrder> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;
    public static final int LINEITEM_FIELD_NUMBER = 4;
    private java.util.List<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem> lineItem_;
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    public java.util.List<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem> getLineItemList() {
      return lineItem_;
    }
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    public java.util.List<? extends com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder> 
        getLineItemOrBuilderList() {
      return lineItem_;
    }
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    public int getLineItemCount() {
      return lineItem_.size();
    }
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem getLineItem(int index) {
      return lineItem_.get(index);
    }
    /**
     * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
     */
    public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder getLineItemOrBuilder(
        int index) {
      return lineItem_.get(index);
    }

    private void initFields() {
      id_ = "";
      lineItem_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLineItemCount(); i++) {
        if (!getLineItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      for (int i = 0; i < lineItem_.size(); i++) {
        output.writeMessage(4, lineItem_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      for (int i = 0; i < lineItem_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, lineItem_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.SalesOrder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.class, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLineItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (lineItemBuilder_ == null) {
          lineItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          lineItemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_descriptor;
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder build() {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder buildPartial() {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder result = new com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (lineItemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            lineItem_ = java.util.Collections.unmodifiableList(lineItem_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.lineItem_ = lineItem_;
        } else {
          result.lineItem_ = lineItemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder) {
          return mergeFrom((com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder other) {
        if (other == com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (lineItemBuilder_ == null) {
          if (!other.lineItem_.isEmpty()) {
            if (lineItem_.isEmpty()) {
              lineItem_ = other.lineItem_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLineItemIsMutable();
              lineItem_.addAll(other.lineItem_);
            }
            onChanged();
          }
        } else {
          if (!other.lineItem_.isEmpty()) {
            if (lineItemBuilder_.isEmpty()) {
              lineItemBuilder_.dispose();
              lineItemBuilder_ = null;
              lineItem_ = other.lineItem_;
              bitField0_ = (bitField0_ & ~0x00000002);
              lineItemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLineItemFieldBuilder() : null;
            } else {
              lineItemBuilder_.addAllMessages(other.lineItem_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getLineItemCount(); i++) {
          if (!getLineItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;
      private java.util.List<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem> lineItem_ =
        java.util.Collections.emptyList();
      private void ensureLineItemIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          lineItem_ = new java.util.ArrayList<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem>(lineItem_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder> lineItemBuilder_;

      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public java.util.List<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem> getLineItemList() {
        if (lineItemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lineItem_);
        } else {
          return lineItemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public int getLineItemCount() {
        if (lineItemBuilder_ == null) {
          return lineItem_.size();
        } else {
          return lineItemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem getLineItem(int index) {
        if (lineItemBuilder_ == null) {
          return lineItem_.get(index);
        } else {
          return lineItemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder setLineItem(
          int index, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem value) {
        if (lineItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLineItemIsMutable();
          lineItem_.set(index, value);
          onChanged();
        } else {
          lineItemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder setLineItem(
          int index, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder builderForValue) {
        if (lineItemBuilder_ == null) {
          ensureLineItemIsMutable();
          lineItem_.set(index, builderForValue.build());
          onChanged();
        } else {
          lineItemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder addLineItem(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem value) {
        if (lineItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLineItemIsMutable();
          lineItem_.add(value);
          onChanged();
        } else {
          lineItemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder addLineItem(
          int index, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem value) {
        if (lineItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLineItemIsMutable();
          lineItem_.add(index, value);
          onChanged();
        } else {
          lineItemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder addLineItem(
          com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder builderForValue) {
        if (lineItemBuilder_ == null) {
          ensureLineItemIsMutable();
          lineItem_.add(builderForValue.build());
          onChanged();
        } else {
          lineItemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder addLineItem(
          int index, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder builderForValue) {
        if (lineItemBuilder_ == null) {
          ensureLineItemIsMutable();
          lineItem_.add(index, builderForValue.build());
          onChanged();
        } else {
          lineItemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder addAllLineItem(
          java.lang.Iterable<? extends com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem> values) {
        if (lineItemBuilder_ == null) {
          ensureLineItemIsMutable();
          super.addAll(values, lineItem_);
          onChanged();
        } else {
          lineItemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder clearLineItem() {
        if (lineItemBuilder_ == null) {
          lineItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          lineItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public Builder removeLineItem(int index) {
        if (lineItemBuilder_ == null) {
          ensureLineItemIsMutable();
          lineItem_.remove(index);
          onChanged();
        } else {
          lineItemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder getLineItemBuilder(
          int index) {
        return getLineItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder getLineItemOrBuilder(
          int index) {
        if (lineItemBuilder_ == null) {
          return lineItem_.get(index);  } else {
          return lineItemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public java.util.List<? extends com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder> 
           getLineItemOrBuilderList() {
        if (lineItemBuilder_ != null) {
          return lineItemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lineItem_);
        }
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder addLineItemBuilder() {
        return getLineItemFieldBuilder().addBuilder(
            com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder addLineItemBuilder(
          int index) {
        return getLineItemFieldBuilder().addBuilder(
            index, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.packt.masteringakka.bookstore.inventory.SalesOrderLineItem lineItem = 4;</code>
       */
      public java.util.List<com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder> 
           getLineItemBuilderList() {
        return getLineItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder> 
          getLineItemFieldBuilder() {
        if (lineItemBuilder_ == null) {
          lineItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItem.Builder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderLineItemOrBuilder>(
                  lineItem_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          lineItem_ = null;
        }
        return lineItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.inventory.SalesOrder)
    }

    static {
      defaultInstance = new SalesOrder(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.inventory.SalesOrder)
  }

  public interface OrderCreatedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;
    /**
     * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
     */
    boolean hasOrder();
    /**
     * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
     */
    com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder getOrder();
    /**
     * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
     */
    com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder getOrderOrBuilder();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.OrderCreated}
   */
  public static final class OrderCreated extends
      com.google.protobuf.GeneratedMessage
      implements OrderCreatedOrBuilder {
    // Use OrderCreated.newBuilder() to construct.
    private OrderCreated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderCreated(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderCreated defaultInstance;
    public static OrderCreated getDefaultInstance() {
      return defaultInstance;
    }

    public OrderCreated getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = order_.toBuilder();
              }
              order_ = input.readMessage(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(order_);
                order_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.class, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.Builder.class);
    }

    public static com.google.protobuf.Parser<OrderCreated> PARSER =
        new com.google.protobuf.AbstractParser<OrderCreated>() {
      public OrderCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderCreated(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OrderCreated> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;
    public static final int ORDER_FIELD_NUMBER = 1;
    private com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder order_;
    /**
     * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
     */
    public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder getOrder() {
      return order_;
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
     */
    public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder getOrderOrBuilder() {
      return order_;
    }

    private void initFields() {
      order_ = com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOrder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrder().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, order_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, order_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.OrderCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.class, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOrderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (orderBuilder_ == null) {
          order_ = com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance();
        } else {
          orderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_descriptor;
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated build() {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated buildPartial() {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated result = new com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (orderBuilder_ == null) {
          result.order_ = order_;
        } else {
          result.order_ = orderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated) {
          return mergeFrom((com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated other) {
        if (other == com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated.getDefaultInstance()) return this;
        if (other.hasOrder()) {
          mergeOrder(other.getOrder());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrder()) {
          
          return false;
        }
        if (!getOrder().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.inventory.OrderDatamodel.OrderCreated) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;
      private com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder order_ = com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder> orderBuilder_;
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public boolean hasOrder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder getOrder() {
        if (orderBuilder_ == null) {
          return order_;
        } else {
          return orderBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public Builder setOrder(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          order_ = value;
          onChanged();
        } else {
          orderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public Builder setOrder(
          com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder builderForValue) {
        if (orderBuilder_ == null) {
          order_ = builderForValue.build();
          onChanged();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public Builder mergeOrder(com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder value) {
        if (orderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              order_ != com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance()) {
            order_ =
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.newBuilder(order_).mergeFrom(value).buildPartial();
          } else {
            order_ = value;
          }
          onChanged();
        } else {
          orderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          order_ = com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.getDefaultInstance();
          onChanged();
        } else {
          orderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder getOrderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      public com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder getOrderOrBuilder() {
        if (orderBuilder_ != null) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          return order_;
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.inventory.SalesOrder order = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrder.Builder, com.packt.masteringakka.bookstore.inventory.OrderDatamodel.SalesOrderOrBuilder>(
                  order_,
                  getParentForChildren(),
                  isClean());
          order_ = null;
        }
        return orderBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.inventory.OrderCreated)
    }

    static {
      defaultInstance = new OrderCreated(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.inventory.OrderCreated)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/proto/orderdatamodel.proto\022+c" +
      "om.packt.masteringakka.bookstore.invento" +
      "ry\"6\n\022SalesOrderLineItem\022\016\n\006bookId\030\002 \002(\t" +
      "\022\020\n\010quantity\030\003 \002(\005\"k\n\nSalesOrder\022\n\n\002id\030\001" +
      " \002(\t\022Q\n\010lineItem\030\004 \003(\0132?.com.packt.maste" +
      "ringakka.bookstore.inventory.SalesOrderL" +
      "ineItem\"V\n\014OrderCreated\022F\n\005order\030\001 \002(\01327" +
      ".com.packt.masteringakka.bookstore.inven" +
      "tory.SalesOrderB\022B\016OrderDatamodelH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrderLineItem_descriptor,
              new java.lang.String[] { "BookId", "Quantity", });
          internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_inventory_SalesOrder_descriptor,
              new java.lang.String[] { "Id", "LineItem", });
          internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_inventory_OrderCreated_descriptor,
              new java.lang.String[] { "Order", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
